language: node_js
node_js:
    - '8.10'

branches:
    only:
        - master

install:
    - pip install --user awscli

jobs:
    include:
        - stage: dev deploy
          script:
              - make deploy STAGE=dev
